### ISSUE TITLE
Error: Could not find or load main class TraktorKeyConverter

### ISSUE THREAD

**Issue by alhadebe** [rosstroha/traktor-key-converter#3]
@rosstroha - I getting this error(Error: Could not find or load main class TraktorKeyConverter) when running java -jar TraktorKeyConverter.jar. Groovy seems to have compiled correctly though.  Any thought will be appreciated

**Comment by rosstroha** [comment]
Hey I'm sorry for the late reply. My energy and thoughts are focused elsewhere these days. I do hope one day to make a website that will do this for you so you don't have to worry about compiling the source to run it.
